esphome:
  name: bob

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "lCm9c1WlzZjVIvTVGpuOUMRsmLhtfdQjBrWbiF+oFKU="

ota:
  password: "d4c416607af8900ec2f26b71f50ccad7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bob Fallback Hotspot"
    password: "gvqWiVmMm3Om"

captive_portal:
    