esphome:
  name: esphome-web-c5c388

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-C5C388"
    password: "lgvFIN7Vc8EE"

captive_portal:


binary_sensor:
  - platform: gpio
    name: "Pin GPIO23"
    pin: 
      number: GPIO23
      mode:
        input: true
        
switch:
  - platform: gpio
    pin: 26
    name: "Garage Door Switch"
    id: open_switch
  - platform: gpio
    pin: 25
    id: relay
    name: "Gate Remote"
    icon: "mdi:gate"
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: relay
#  - platform: gpio
#    pin: GPIO26
#    name: "Garage Door Close Switch"
#    id: close_switch
cover:
  - platform: template
    name: "Garage Door"
    open_action:
      # Cancel any previous action
#      - switch.turn_off: close_switch
      # Turn the OPEN switch on briefly
      - switch.turn_on: open_switch
      - delay: 1s
      - switch.turn_off: open_switch
    close_action:
      - switch.turn_on: open_switch
      - delay: 1s
      - switch.turn_off: open_switch
#      - switch.turn_off: open_switch
#      - switch.turn_on: close_switch
#      - delay: 0.1s
#      - switch.turn_off: close_switch
#    stop_action:
#      - switch.turn_off: close_switch
#      - switch.turn_off: open_switch
    optimistic: true
    assumed_state: true
    
# Example configuration entry
sensor:
  - platform: dht
    pin: 
      number: GPIO22
      mode:
        input: true
    temperature:
      name: "Garage Temperature"
    humidity:
      name: "Garage Humidity"
    update_interval: 60s   
 
