esphome:
  name: fountain-pump-2

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Fd/9+SLlwoU0B9q/KxW1u4WBeap/bm8mRWy6zf1GbS8="

ota:
  password: "0e5e561567dccd1cc2685efb210e0b03"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fountain-Pump-2 Fallback Hotspot"
    password: "ZPwjbLkAEUTP"

captive_portal:
    