
esphome:
  name: garage
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key_1

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage Fallback Hotspot"
    password: !secret hotspot_wifi_password

captive_portal:

switch:
  - platform: gpio
    pin: D5
    name: "Door relay"
    id: door_relay
    internal: true
    on_turn_on:
    - delay: 250ms
    - switch.turn_off: door_relay
    
binary_sensor:
  - platform: template
    name: "Garage Door Is Jammed"
    id: is_jammed
    device_class: problem
  - platform: template
    name: "Garage Door Is Open"
    id: is_open
    device_class: garage_door
    
  - platform: gpio
    pin:
      number: D1
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Garage Door Close Sensor"
    id: close_endstop_binary_sensor
    internal: true
    on_press:
       - cover.template.publish:
           id: garage_door
           state: CLOSED
           current_operation: IDLE
       - binary_sensor.template.publish:
          id: is_jammed
          state: OFF
       - binary_sensor.template.publish:
          id: is_open
          state: OFF
    on_release: 
       - cover.template.publish:
           id: garage_door
           current_operation: OPENING    
       - binary_sensor.template.publish:
          id: is_open
          state: ON
       - delay: 25s
       - if:
           condition:
             binary_sensor.is_off: open_endstop_binary_sensor
           then: 
              - binary_sensor.template.publish:
                  id: is_jammed
                  state: ON
  - platform: gpio
    pin:
      number: D2
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Garage Door Open Sensor"
    id: open_endstop_binary_sensor
    internal: true
    on_press:
       - cover.template.publish:
           id: garage_door
           state: OPEN
           current_operation: IDLE
       - binary_sensor.template.publish:
          id: is_jammed
          state: OFF
    on_release: 
       - cover.template.publish:
           id: garage_door
           current_operation: CLOSING  
       - delay: 25s
       - if:
           condition:
             binary_sensor.is_off: open_endstop_binary_sensor
           then: 
              - binary_sensor.template.publish:
                  id: is_jammed
                  state: ON


cover:
  - platform: template
    id: garage_door
    name: "Garage Door"
    device_class: garage
    open_action:
      - switch.turn_on: door_relay
    close_action:
      - switch.turn_on: door_relay
    stop_action:
      - switch.turn_on: door_relay