esphome:
  name: trailer

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "On1YQLsFx5URFb4BAgzYrQf8VN9SWUR1ZKY1XU52ha4="

ota:
  password: "5f9f00ff6ecf9930e4cf2040f26bbcb7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Trailer Fallback Hotspot"
    password: "LsQ08qwKXvuI"

captive_portal:
   

# Example configuration entry
dallas:
  - pin: GPIO23

# Note you don't have to add any sensors at this point    

# Example configuration entry
i2c:
  sda: GPIO21
  scl: GPIO22

display:
  - platform: lcd_pcf8574
    dimensions: 18x4
    address: 0x27
      #  address: 0x3F
    lambda: |-

      it.print("Hello World!");